version: "2"
services:
  nginx:
      build:
          context: ./nginx
      ports:
          - "8080:80"
      volumes:
          - ${APP_PATH}:/var/app
  fpm:
      build:
          context: ./fpm
      volumes:
          - ${APP_PATH}:/var/app
      expose:
          - "9000"
      environment:
          - DB_HOST=${MYSQL_HOST}
          - DB_USERNAME=${MYSQL_USER}
          - DB_PASSWORD=${MYSQL_PW}
          - DB_DATABASE=${MYSQL_DB}
  db:
      image: mariadb
      environment:
          - MYSQL_ROOT_PASSWORD=${MYSQL_PW}
          - MYSQL_DATABASE=${MYSQL_DB}
      volumes:
          - ${DB_PATH}:/var/lib/mysql
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
       - PMA_HOST=db
      restart: always
      ports:
        - "9090:80"
      volumes:
       - /sessions        
  
